services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      target: runner
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_STRAPI_URL: ${NEXT_PUBLIC_STRAPI_URL}
      NEXT_PUBLIC_STRAPI_ASSETS_URL: ${NEXT_PUBLIC_STRAPI_ASSETS_URL}
      STRAPI_API_TOKEN: ${STRAPI_API_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    depends_on:
      strapi:
        condition: service_healthy
    ports:
      - "9000:3000"
    restart: unless-stopped

  strapi:
    build:
      context: .
      dockerfile: Dockerfile.strapi
      target: runner
    env_file:
      - ./strapi/.env
    environment:
      NODE_ENV: production
      PUBLIC_URL: ${STRAPI_PUBLIC_URL}
    ports:
      - "1337:1337"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - database.env
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "$POSTGRES_USERNAME", "-U", "$POSTGRES_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 5
